FROM php:7.0.6-fpm-alpine
MAINTAINER Blake Cerecero blake@digitalblake.com

RUN docker-php-ext-install -j $(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    iconv gd mbstring fileinfo curl xmlreader xmlwriter spl ftp mysqli

VOLUME /var/www/html